[project]
name = 'Peer-to-Peer-Lending-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lender-matching]
path = 'contracts/lender-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.loan-request]
path = 'contracts/loan-request.clar'
clarity_version = 2
epoch = 2.5

[contracts.repayment-management]
path = 'contracts/repayment-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
